### ISSUE TITLE
UniswapError: No routes found on Mainnet

### ISSUE THREAD

**Issue by it-n-ova** [joshstevens19/simple-uniswap-sdk#16]
Created liquidity pool at pair MTT > USDT on Mainnet.
Set up disableMultihops: false, but it still works only at MTT <-> USDT, on any other pair i got an error like:
UniswapError: No routes found for MTT > DAI

On uniswap app works great with any other tokens.

```
fromTokenContractAddress: '0xe0c15f5066FCbAfad6d1972125fB0cC1d2200bbe',
toTokenContractAddress: '0x6b175474e89094c44da98b954eedeac495271d0f',
uniswapVersions: [UniswapVersion.v2, UniswapVersion.v3],
chainId: 1,
settings: new UniswapPairSettings({
	slippage: 0.01,
	deadlineMinutes: 20,
	disableMultihops: false,
	uniswapVersions: [UniswapVersion.v2, UniswapVersion.v3]
})
```

I am stuck, please help to find out solution.

**Comment by joshstevens19** [comment]
hey thanks for this issue, right now `UniswapVersion.v3` only handles direct routes aka MIT > DAI it doesn't look at any other routes to take at the current time mainly because v3 was so new when we supported this. This is something we need to bring into the lib, will try to get some time to look and support this logic as soon as I get some time. 

Sorry for the inconvenience

**Comment by joshstevens19** [comment]
now looks at many routes
