### ISSUE TITLE
Invalid from or to address on custom chain?

### ISSUE THREAD

**Issue by Divide-By-0** [joshstevens19/simple-uniswap-sdk#47]
Both of these addresses definitely exist, but INIT_CODE_HASH on this chan is likely different, so the pair calculation is likely different. Any idea what this error could mean? This is when i make a new UniswapPair and run createFactory on a non-eth chain. I don't have a canonical Multicall address here so I left that blank, is that OK? Or should I deploy my own multicall contract?

**Comment by joshstevens19** [comment]
hey if using a custom chain you need to map a custom network

<img width="766" alt="Screenshot at Aug 24 01-24-53" src="https://user-images.githubusercontent.com/18472422/186288588-349aa416-58d4-4918-bbf1-1c3e288f4723.png">

yes you need to deploy a multicall contract if not defined in > https://github.com/joshstevens19/ethereum-multicall

**Comment by joshstevens19** [comment]
also you may need to use `clonseUniswapContractDetails` if you deployed uniswap somewhere else as a fork

**Comment by Divide-By-0** [comment]
Yes, I added all of those and deployed my own multi-call contract, and then it past this step. However, it still says Uniswaperror: excessive input amount, when I try to initiate a trade. Google says I should increase the slippage, but even at 0.80 slippage, it still seems to occur.

**Comment by YauhenPachankou** [comment]
@joshstevens19  @Divide-By-0  Hi! 

I have the same issue on Arbitrum Goerli network (chainId ===  421613),  I have added customNetwork and cloneUniswapContractDetails, but it still doesn't work. And can i skip nativeCurrency and nativeWrappedTokenInfo ?
So, maybe you can see what the problem is ? Thanks !
![Screenshot 2023-07-24 at 16 42 47](https://github.com/joshstevens19/simple-uniswap-sdk/assets/40360289/0ba55b26-4657-4abe-b132-350e05eae334)
